window.LifeGame = window.LifeGame || {};

window.LifeGame.CONFIG = {
  buildId: "20260717-offline-1",
  version: 3,
  eventRevision: 2026071606,
  stateKey: "disordered-life-state-v1",
  archiveKey: "disordered-life-archive-v1",
  achievementKey: "disordered-life-achievements-v1",
  traitKey: "disordered-life-traits-v1",
  collectibleKey: "disordered-life-collectibles-v1",
  tributeKey: "disordered-life-tribute-v1",
  dailyTaskKey: "disordered-life-daily-tasks-v1",
  hiddenEndingKey: "disordered-life-hidden-ending-v1",
  blackMarketKey: "disordered-life-black-market-v1",
  casinoKey: "disordered-life-casino-v1",
  assets: {
    background: "./assets/generated/life-crossroads-bg.6dc93a1f.webp",
    lin: "./assets/generated/lin-lan-boss.8adf43cd.webp",
    qin: "./assets/generated/qin-mei-patron.e987cdd9.webp",
    su: "./assets/generated/su-fei-streamer.3233b8aa.webp",
    shen: "./assets/generated/shen-jingqiu-tutor.65ea9410.webp",
    reina: "./assets/generated/takahashi-reina-teacher.588c8a86.webp",
    miki: "./assets/generated/sato-miki-landlady.a0469ae1.webp",
    mari: "./assets/generated/kanzaki-mari-cult-leader.1ee8a72c.webp",
    evelyn: "./assets/generated/evelyn-hart-professor.4212a2dd.webp",
    claire: "./assets/generated/claire-morgan-executive.caca13ac.webp",
    ruth: "./assets/generated/ruth-carter-ranch-owner.f09949f9.webp",
    restaurantCouple: "./assets/generated/restaurant-couple-portrait.ffeb13e8.webp",
    agencyCouple: "./assets/generated/agency-couple-portrait.ee5f0b66.webp",
    qinghe: "./assets/generated/qinghe-retreat-manager.ddf3fbc4.webp",
    ciyun: "./assets/generated/ciyun-retreat-manager.8c2295f7.webp",
    agnes: "./assets/generated/agnes-retreat-manager.899f04b1.webp",
    kaori: "./assets/generated/kuroda-kaori-supervisor.4655d930.webp",
    victoria: "./assets/generated/victoria-hayes-supervisor.6f6ddf48.webp",
    streetThug: "./assets/generated/street-thug-portrait.65f95e04.webp",
    beggar: "./assets/generated/beggar-portrait.8c3b9943.webp",
    japanOfficial: "./assets/generated/japanese-female-official.12246494.webp",
    usaOfficial: "./assets/generated/american-female-official.1091ce78.webp",
    playerRoom: "./assets/generated/player-room-protagonists.8e05e60f.webp",
    protagonistMaleBase: "./assets/generated/protagonist-male-base.15d3eb1b.webp",
    protagonistFemaleBase: "./assets/generated/protagonist-female-base.055bb894.webp",
    protagonistMaleCharacterSet: "./assets/generated/protagonist-male-character-set-v2.10e1268e.webp",
    protagonistFemaleCharacterSet: "./assets/generated/protagonist-female-character-set-v2.731ba55c.webp",
    protagonistMaleTributeSet: "./assets/generated/protagonist-male-tribute-set.7874d3b1.webp",
    protagonistFemaleTributeSet: "./assets/generated/protagonist-female-tribute-set.ccaff5a6.webp",
    protagonistMaleJapanSet: "./assets/generated/protagonist-male-japan-set-v3.eb840e3a.webp",
    protagonistFemaleJapanSet: "./assets/generated/protagonist-female-japan-set-v3.5887d10d.webp",
    protagonistMaleUSASet: "./assets/generated/protagonist-male-usa-set-v3.5cb37ce3.webp",
    protagonistFemaleUSASet: "./assets/generated/protagonist-female-usa-set-v2.7fe713d6.webp",
    protagonistMaleTraitSet: "./assets/generated/protagonist-male-trait-set-v2.32aa0a2c.webp",
    protagonistFemaleTraitSet: "./assets/generated/protagonist-female-trait-set-v2.e173c78c.webp",
  },
  initialStats: {
    knowledge: 40,
    money: 20,
    health: 70,
    social: 45,
    autonomy: 45,
    dependence: 15,
    dignity: 70,
    shame: 0,
  },
  statMeta: {
    knowledge: "学识",
    money: "资金",
    health: "健康",
    social: "人际",
    autonomy: "自主",
    dependence: "依赖",
    dignity: "尊严",
    shame: "羞耻",
  },
};
